### ISSUE TITLE
1,104.96% failed the percent.valid() test

### ISSUE THREAD

**Issue by xywang68** [zdroid/percent#1]
percent = require('percent');
var data = '1,104.96%';
result = percent.valid(data);
console.log(result);
 // result was false. Should it be true?

**Comment by zdroid** [comment]
I hope this does the trick. Thank you for reminding me of that kind of writing numbers. :tada:

**Comment by xywang68** [comment]
I pulled the latest code and confirmed it is fixed. Thank you.
Do you mind updating the version number so that normal 'npm insall' will pick up this change?

**Comment by zdroid** [comment]
@xywang68 It should be published now as v1.2.0. It's always good to see a fresh module release. :shipit:

**Comment by xywang68** [comment]
Another question:
```
var data = '1104.96';
result = percent.valid(data);
console.log(result);
```
returned true. So the valid() function does not check for the '%' sign? Is this intended? If yes can you specify in the function spec?

**Comment by zdroid** [comment]
Yeah @xywang68, it's intended, because 100% = 1. And some people might just want to write it the other way.

I think it's already written in function description:
> Checks if value is valid percent value. It is valid if it's number, number-like string (e.g. '10', not 10), or string with number and percent sign. Spaces are allowed in strings.

But if there's anything to add, please tell me. :smile:
