### ISSUE TITLE
SyntaxError while building React app that uses percent

### ISSUE THREAD

**Issue by rafaeleyng** [zdroid/percent#2]
Hi there

I have a React app built with `create-react-app@0.9.5` that uses `percent@2.0.0`.

When I run `yarn run build` to build optimized bundle, I get

```
yarn run v0.22.0
$ react-scripts build
Creating an optimized production build...
Failed to compile.

static/js/main.190dfa22.js from UglifyJs
SyntaxError: Unexpected token: operator (>) [./~/percent/index.js:12,0]
```

I'll actually won't be using `percent` anymore in this project (that is a toy project after all) since I'll probably will implement myself the calculation, but just to let you know.

In development mode (`yarn start`) it works just fine.

**Comment by zdroid** [comment]
Does [this fix](https://github.com/AngularClass/angular2-webpack-starter/issues/853#issuecomment-278542609) work? People are reporting similar issues with ES6, so please check is the described problem your case.

**Comment by zdroid** [comment]
I'll close this. If you have similar issues in the future, tell me.
